version: '3.1'

services:

  wordpress:
    build: ../
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

    volumes:
      - ./mounted_folder/wordpress:/var/www/html
      - ./mounted_folder/xdebug:/tmp

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mounted_folder/db:/var/lib/mysql
      - ./mounted_folder/dump.sql:/docker-entrypoint-initdb.d/dump.sql


networks:
  default:
    name: wp-network
